name: Node CI

on: [push, pull_request]

jobs:
  build:
    name: Build Job
    runs-on: macos-latest
    strategy:
      matrix:
        node: [10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn install --frozen-lockfile
        yarn run build:production
        yarn test
